# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_libro_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
