# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171019_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='prestado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
